server:
  port: 9011

forest:
  backend: okhttp3 # 后端HTTP API： okhttp3
  max-connections: 1000 # 连接池最大连接数，默认值为500
  max-route-connections: 500 # 每个路由的最大连接数，默认值为500
  timeout: 3000 # 请求超时时间，单位为毫秒, 默认值为3000
  connect-timeout: 3000 # 连接超时时间，单位为毫秒, 默认值为2000
  ssl-protocol: SSLv3 # 单向验证的HTTPS的默认SSL协议，默认为SSLv3
  logEnabled: false # 打开或关闭日志，默认为true
  log-request: false # 打开/关闭Forest请求日志（默认为 true）
  log-response-status: false # 打开/关闭Forest响应状态日志（默认为 true）
  log-response-content: false # 打开/关闭Forest响应内容日志（默认为 false）