server:
  port: 8010

spring:
  application:
    name: provider-payment-sentinel
  cloud:
    nacos:
      discovery:
        #配置Nacos地址
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapperLocations: com/cmj/example/xml/*.xml
  type-aliases-package: com.cmj.example.vo    # 所有Entity别名类所在包

management:
  endpoints:
    web:
      exposure:
        include: '*'