package com.cmj.example.mapper;

import com.cmj.example.base.TaskRecordBase;
import com.cmj.example.base.TaskRecordBaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskRecordBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    long countByExample(TaskRecordBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    int insert(TaskRecordBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") TaskRecordBase record, @Param("selective") TaskRecordBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    TaskRecordBase selectOneByExample(TaskRecordBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    TaskRecordBase selectOneByExampleSelective(@Param("example") TaskRecordBaseExample example, @Param("selective") TaskRecordBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    TaskRecordBase selectOneByExampleWithBLOBs(TaskRecordBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    List<TaskRecordBase> selectByExampleSelective(@Param("example") TaskRecordBaseExample example, @Param("selective") TaskRecordBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    List<TaskRecordBase> selectByExampleWithBLOBs(TaskRecordBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    List<TaskRecordBase> selectByExample(TaskRecordBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    TaskRecordBase selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TaskRecordBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    TaskRecordBase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaskRecordBase record, @Param("example") TaskRecordBaseExample example, @Param("selective") TaskRecordBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TaskRecordBase record, @Param("example") TaskRecordBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaskRecordBase record, @Param("example") TaskRecordBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(@Param("record") TaskRecordBase record, @Param("selective") TaskRecordBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TaskRecordBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaskRecordBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<TaskRecordBase> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_record
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<TaskRecordBase> list, @Param("selective") TaskRecordBase.Column ... selective);
}