server:
  port: 9008

spring:
  application:
    name: consumer-payment

eureka:
  instance:
    instance-id: consumer-zipkin-9008

  client:     #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://127.0.0.1:7002/eureka,http://127.0.0.1:7003/eureka

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.cmj.example.service.IPaymentFeignService: debug