server:
  port: 8004

spring:
  application:
    name: provider-payment-eureka-8004
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka,http://127.0.0.1:7003/eureka  # 集群版


mybatis:
  mapperLocations: com/cmj/example/xml/*.xml
  type-aliases-package: com.cmj.example.vo    # 所有Entity别名类所在包




