server:
  port: 9010

spring:
  application:
    name: consumer-payment-sentinel
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: consumer-payment-sentinel
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://provider-payment-nacos

# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 3000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 3000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.cmj.example.service.IPaymentFeignService: debug